export const PAKISTAN_CITIES = [
	'Abbottabad',
	'Attock',
	'Badin',
	'Bagh',
	'Bahawalnagar',
	'Bahawalpur',
	'Bannu',
	'Bhakkar',
	'Bhimber',
	'Bhit Shah',
	'Buner',
	'Chakwal',
	'Charsadda',
	'Chiniot',
	'Chitral',
	'Dera Ghazi Khan',
	'Dera Ismail khan',
	'Faisalabad',
	'Gilgit',
	'Gujranwala',
	'Gujrat',
	'Gwadar',
	'hafizabad',
	'Haripur',
	'Hasanabdal',
	'Hyderabad',
	'Islamabad',
	'Jamshoro',
	'Jhang',
	'Jhelum',
	'Karachi',
	'Khairpur',
	'Khanewal',
	'Khanpur',
	'Khushab',
	'Khuzdar',
	'Kohat',
	'Kotli',
	'Lahore',
	'Lakki Marwat',
	'Larkana',
	'Lasbella',
	'Layyah',
	'Liaquatpur',
	'Lodhran',
	'Loralai',
	'Malakand',
	'Mansehra',
	'Mardan',
	'Mianwali',
	'Mirpur',
	'Mirpurkhas',
	'Multan',
	'Murree',
	'Muzaffarabad',
	'Muzaffargarh',
	'Nankana Sahib',
	'Narowal',
	'Nawabshah',
	'Nerian Shariff',
	'Nowshera',
	'Okara',
	'Pakpattan',
	'Pattoki',
	'Peshawar',
	'Poonch',
	'Quetta',
	'Rabwah',
	'Rahim yar Khan',
	'Rawalpindi',
	'Risalpur',
	'Sadiqabad',
	'Sahiwal',
	'Sargodha',
	'Sheikhupura',
	'Sialkot',
	'Skardu',
	'Sukkur',
	'Swabi',
	'Swat',
	'Tank',
	'Thatta',
	'Toba Tek Singh',
	'Turbat',
	'Upperdir',
	'Vehari',
];

export const KARACHI_DEGREE_LEVELS = [
	'Matric / O Level',
	'Intermediate / A Level',
	'Undergraduate',
	'Graduate',
	'Postgraduate',
	'Certification',
	'Diplomas & Courses',
];

export const KARACHI_UNDER_GRADUATE_PROGRAMS = [
	'Accelerated occupational Therapy',
	'Accounting & Finance',
	'Actuarial & Risk Management',
	'Advertising',
	'Aerospace Engineering',
	'Agriculture & Agribusiness Management',
	'Anesthesia',
	'Anesthesiology',
	'Applied Bioscience',
	'Applied Chemistry',
	'Applied Physics',
	'Arabic',
	'Architecture',
	'Artificial Intelligence',
	'Arzu Program Languages & Literature',
	'Automotive Engineering',
	'Aviation Management',
	'Avionics Engineering',
	'Banking & Finance',
	'Basic Financial Reporting',
	'Bio Medical',
	'Biochemistry',
	'Bioinformatics',
	'Biology',
	'Biomedical Engineering',
	'Biosciences',
	'Biotechnology',
	'Botany',
	'Business Administration',
	'Business Information Technology',
	'Business Management',
	'Business Studies',
	'Cardiology',
	'Chemical',
	'Chemical Engineering',
	'Chemical Pathology',
	'Chemical Technology',
	'Chemistry',
	'Civil Engineering',
	'Civil Engineering Technology',
	'Civil Technology',
	'Clinical',
	'Clinical Laboratory Sciences',
	'Commerce',
	'Communication Design',
	'Communicaton & Media Studies',
	'Comparative Liberal Studies',
	'Computational Finance',
	'Computer & Information Technology',
	'Computer Arts',
	'Computer Engineering',
	'Computer Science',
	'Computer System Engineering',
	'Computer Systems',
	'Criminology',
	'Critical Care Sciences',
	'Data Science',
	'Decision Making Skills For Managers',
	'Dental Care Professional',
	'Dental Hygiene',
	'Dental Sciences',
	'Dental Surgery',
	'Dental Technology',
	'Dentistry',
	'Design',
	'Development Studies',
	'Diagnostic Radiology',
	'Dialysis Technology',
	'Doctor Physical Therapy',
	'Eastern Medicine & Surgery',
	'Eco',
	'Law & International Relations',
	'Eco',
	'Media & International Relations',
	'Economics',
	'Economics & Finance',
	'Education',
	'Electrical',
	'Electrical Engineering Technology',
	'Electrical Engineering Telecommunication Engineering',
	'Electrical Engineering.',
	'Electrical Technology',
	'Electronic Engineering',
	'Electronic Engineering Technology',
	'Electronics',
	'Electronics Engineering',
	'Electronics Technology',
	'English',
	'English Linguistics',
	'English Literature',
	'Entrepreneurship',
	'Enviromental Science',
	'Environmental Studies',
	'Epidemiology & Public Health',
	'Fashion Designing',
	'Film & Tv',
	'Finance',
	'Financial Reporting Of Corporate Entities',
	'Fine Arts',
	'Food & Technology',
	'Food Engineering',
	'Food Science & Technology',
	'Gastroenterology',
	'General History',
	'General Surgery',
	'Geography',
	'Geoinformatics Engineering',
	'Geology',
	'Geophysics',
	'Gynecology & Obstetrics',
	'Health & Safety Environment',
	'Health Care & Hospital Management',
	'Health Informatics',
	'Health Management',
	'Health Physical Education & Sports Science',
	'Hematology',
	'Human Nutrition & Dietetics',
	'Human Resource Management',
	'Industrial Chemistry',
	'Industrial Design',
	'Industrial Engineering',
	'Industrial Engineering & Management',
	'Industrial Management',
	'Information System',
	'Information Technology',
	'Interior Designing',
	'Internal Medicine',
	'International Relations',
	'International Tourism & Hotel Management',
	'Islamic Finance',
	'Islamic History',
	'Islamic Learning',
	'Islamic Studies',
	'Joint Business & Psychology',
	'Law',
	'Library & Information Science',
	'Library Science',
	'Logistics & Supply Management',
	'Management',
	'Management Information Systems',
	'Management Sciences',
	'Marine Science',
	'Marketing',
	'Mass Communication',
	'Materials Engineering',
	'Mathematical Science',
	'Mathematics',
	'Mathematics & Economics',
	'Mechanical Engineering',
	'Mechanical Engineering Technology',
	'Mechanical Technology',
	'Mechatronic Engineering',
	'Mechatronics',
	'Media Digital Marketing',
	'Media Film & Tv Production',
	'Media Studies',
	'Media Studies & Communication Studies',
	'Medical Laboratory Science',
	'Medical Technology',
	'Medicine',
	'Medicine & Surgery',
	'Metallurgical Engineering',
	'Metallurgy & Materials Engineering',
	'Microbiology',
	'Military Art & Science',
	'Mob Comm & Security',
	'Molecular Biology & Biotechnology',
	'Naval Architecture',
	'Nursing',
	'Nutritional Science',
	'Occupational Therapy',
	'Operation Theater Sciences',
	'Oral & Maxillofacial Surgery',
	'Oral Biology',
	'Oral Pathology',
	'Organizational Communication',
	'Orthopaedics',
	'Overview Of Taxation',
	'Pathology',
	'Period ontology',
	'Petroleum & Gas Engineering',
	'Petroleum Engineering',
	'Pharmacy',
	'Philosophy',
	'Physical Therapy',
	'Physics',
	'Physiology',
	'Physiotherapy',
	'Political Science',
	'Polymer & Petrochemical  Engineering',
	'Polymer Engineering',
	'Power Engineering',
	'Primary Education',
	'Project Management',
	'Prosthetics & Orthotics',
	'Psychology',
	'Public Administration',
	'Radiology',
	'Respiratory Therapy',
	'Sindhi',
	'Social Development & Policy',
	'Social Science',
	'Social Work',
	'Sociology',
	'Software Engineering',
	'Space & Technology',
	'Spatial Information Technology',
	'Special Education',
	'Speech Language Pathology',
	'Statistics',
	'Statistics and Business Analytics',
	'Supply Chain Management',
	'Surgery',
	'Sustainable Environmental Design',
	'Techniques For Managing Cost',
	'Technology & Policy',
	'Telecommunication',
	'Telecommunication Engineering',
	'Textile & Fashion Design',
	'Textile Designing',
	'Textile Engineering',
	'Textile Management & Marketing',
	'Textile Science',
	'Total Quality Management',
	'Urban Engineering',
	'Urdu',
	'Urology',
	'Usool Ud Din',
	'Veterinary Medicine',
	'Veterinary Science',
	'Visual Effects & Compositing',
	'Zoology',
];
